# -*- coding: utf-8 -*-
"""26.05.2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6Ly3ssvbJtAPS-HmcIxGCD5yQUnIAqJ
"""

print ("Hello world")